### ISSUE TITLE
Can not Drag & Drop Folders with Images in the data area

### ISSUE THREAD

**Issue by andko76** [maikherbig/AIDeveloper#1]
![Error-Message](https://user-images.githubusercontent.com/59789165/72239424-4fbe3280-35e1-11ea-9b2d-160b245f0451.png)

If I Drag&Drop a Folder with Images inside the input-area, then i get this error, if i have only one image inside the Folder, then i get no error. I tryed different Image-Formates (jpg / png / bmp), no difference.
(I used the compiled version AIDeveloper_0.0.4.exe from Github)

I hope you can help me, because i like your tool, the training-videos are very impressive!
Thank you

**Comment by maikherbig** [comment]
Hi,
thanks for bringing up this issue. Unfortunately, I cannot reproduce the issue. Could you send me some of the images you were trying to import? Could you try to unzip and load these images here (they are part of CIFAR10)?:
[someimgs.zip](https://github.com/maikherbig/AIDeveloper/files/4052849/someimgs.zip)

**Comment by andko76** [comment]
Hi Maik,
thanks for fast response, i done same more tests, also with the source code and found the issue. Some of my images had not exactly the same dimensions (270x 420 and 271x421), this lead to the error during images=np.array(images) Function. Array items should have the same dimensions, this was my conclusion for the error. I resized all images with an python script to 270 x 420, now it works.

It would be nice, if you could integrated a check and error message for this, or a function to resize the images inside **your fantastic tool** !!! 

I have an additional question: I have greyscale images (1 dimension) and i like to train for example a VGG, this do not work, because 3 dimensions are expected. Is there an option, to copy/clone the 1 grayscale dimension to the 2. / 3. dimension or have you a other solution for this ?

And i will test the new version 0.0.5  :-))

Thanks

**Comment by maikherbig** [comment]
WOW, Thanks so much! I did actually not consider that differently sized images could occur in the same class. I will follow your suggestion and include a check and error message since I don't know which would be the best automatic resizing option (padding or zooming small images; cropping the large images,...). It is great that you found a solution.

Now to your second question:
This is already integrated. Please find the "Color Mode" option. Set it to RGB and AIDeveloper will automatically triplicate the 1st channel.
This is defined in 
In AIDeveloper_0.0.4.py on line 231
and in AIDeveloper 0.05 there is a special script for image processing: aid_img.py. There you find the same operation on line 58:

        if color_mode=='RGB':#If the user want to use RGB, but did only load Grayscale images, simply copy the information to all 3 channels
            images = np.stack((images,)*3, axis=-1)
            print("Copied information to all three channels to convert Grayscale RGB")

In AIDeveloper_0.05, I optimized the image augmentation processing, since I figured out that they took often more time than the actual training process. Some image augmentation methods are now even 7 times faster (those functions are also defined in aid_img.py).

![Color_Mode](https://user-images.githubusercontent.com/14074051/72380087-f820e380-3714-11ea-97d3-fd0f6b6c8415.png)

**Comment by maikherbig** [comment]
WOW, Thanks so much! I did actually not consider that differently sized images could occur in the same class. I will follow your suggestion and include a check and error message since I don't know which would be the best automatic resizing option (padding or zooming small images; cropping the large images,...). It is great that you found a solution.

Now to your second question:
This is already integrated. Please find the "Color Mode" option. Set it to RGB and AIDeveloper will automatically triplicate the 1st channel.
This is defined in 
In AIDeveloper_0.0.4.py on line 231
and in AIDeveloper 0.05 there is a special script for image processing: aid_img.py. There you find the same operation on line 58:

        if color_mode=='RGB':#If the user want to use RGB, but did only load Grayscale images, simply copy the information to all 3 channels
            images = np.stack((images,)*3, axis=-1)
            print("Copied information to all three channels to convert Grayscale RGB")

In AIDeveloper_0.05, I optimized the image augmentation processing, since I figured out that they took often more time than the actual training process. Some image augmentation methods are now even 7 times faster (those functions are also defined in aid_img.py).

![Color_Mode](https://user-images.githubusercontent.com/14074051/72382341-58b21f80-3719-11ea-87da-ce216b9f5cb1.png)

**Comment by maikherbig** [comment]
Btw. AIDeveloper is optimized for squared images. So either use 
-Input image size = 270 (the longer side of 420 pixels will be cropped to 270), or
-Input image size = 420 (the shorter side of 270 pixels will be padded to 420), or
-something in between

**Comment by maikherbig** [comment]
Hi,
as I already pointed out, AIDeveloper was optimized for squared images. To support loading of rectangular images, I adjusted the function gen_crop_img in aid_img.py. Using symmetric cropping and padding, the rectangular images will be converted to squared images. Hence, for "portrait"-images (higher than wide), an upper and lower part will be cut. Please find this new function in the latest release (https://github.com/maikherbig/AIDeveloper/releases/tag/0.0.5_dev1).
I hope this helps you!

**Comment by andko76** [comment]
Hi Maik,
thank you for your fast improvement, sorry for late answer, but in the last days i had no time.
Now i checked again the dataset with the different image sizes with the new AID_0.0.5_dev1 and now you check the dimensions and show a information window with a hint 👍  

See you a possibility not only to show this hint and give the user the possibility to choose between
cropping , padding, resize to change automatically the image sizes to the same format ?

I tested AID also on a system with GPU, but I see also the Device Type: CPU, support AID a GPU?
If yes, what i have to do?

Another nice feature could be a heatmap for classified images to show, which features from the image have the main influence for classification (learned features).

You wrote, that you support now not symmetric images through cropping and padding. I also tested these feature with some pictures with 271 x 411 pixels, as Input Image Size i choosed 270 pixel.

i was surprised, because the cropping and padding result was a image size from 382 x 383 pixel, this is a not symmetric result, is this a mistake?

### Copy from Session Window:
_Copied information to all three channels to convert Grayscale RGB
I will crop: 14 pixels in height
I will pad in width: 56 pixels on each side
I'm loading all images (from disk)
Image size after padding width :(3, 411, 383, 3),(3,)
Image size after cropping height:(3, 382, 383, 3),(3,)
Final size:(3, **382, 383**, 3),(3,)
Copied information to all three channels to convert Grayscale RGB
I will crop: 14 pixels in height
I will pad in width: 56 pixels on each side
I'm loading all images (from disk)
Image size after padding width :(3, 411, 383, 3),(3,)
Image size after cropping height:(3, 382, 383, 3),(3,)
Final size:(3, **382, 383**, 3),(3,)
Getting dictionary for class_weight
Length of DATA (in RAM) = 3
Export original images_

### afterwards I got following error message in the session window:
_Traceback (most recent call last):
  File "AIDeveloper_0.0.5_dev1.py", line 245, in run
    result = self.fn(*self.args, **self.kwargs)
  File "AIDeveloper_0.0.5_dev1.py", line 7478, in action_fit_model_worker
    aid_bin.write_rtdc(new_modelname.split(".model")[0]+'_Valid_Data.rtdc',rtdc_path_valid,X_valid,Indices,cropped=save_cropped,color_mode=self.get_color_mode())
  File "aid_bin.py", line 178, in write_rtdc
    index_new = np.array(range(1,np.sum(np.array([len(I) for I in Indices]))+1)) #New index. Will replace the existing index in order to support viewing imges in shapeout
TypeError: 'numpy.float64' object cannot be interpreted as an integer_

Thanks so far
Andre

**Comment by maikherbig** [comment]
Hi Andre,
thank you so much for your comments! 
1.) adjusting unequal image sizes (one folder contains multiple image sizes):
I think I will create a tool to help users to cope with such datasets. Thanks for the hint. I'll keep it in mind.

2.) AID and GPU:
This is possible, but only in the script-based version (not the .exe). When you installed tensorflow-gpu correctly, AID will automatically use the GPU. Installing all tools to get it working with GPU is a bit more tricky as one would expect. Back in 2016, I followed this tutorial here:
https://www.youtube.com/watch?v=r7-WPbx8VuY
which should still be valid. Otherwise maybe check out other, newer tutorials like:
https://towardsdatascience.com/installing-tensorflow-with-cuda-cudnn-and-gpu-support-on-windows-10-60693e46e781

3.)Heatmap to show model-attention:
This would be a really cool feature and I'd love to implement it. Do you know some link or library that is good for this purpose?

4.) Non-symmetric images with **odd** dimensions:
Nice catch!!! I totally forgot about the case that someone wants to use images with an odd number of pixels in height or width. To fix that, I implemented a function called check_squared in aid_img.py, which basically removes one column or one row from the image to bring it to a squared format. This is only required if the initial image has an odd dimension. Please find the corresponding **new release** which fixes this issue:
https://github.com/maikherbig/AIDeveloper/releases/tag/0.0.5_dev2 

5.) I set "Input image size" to 270, but in the console it says "final size is 283":
This is not an error but intended behavior which I will explain now. One major advantage when working with images is that you can do image augmentation for example rotation. When you rotate the image, there will be missing information in the edges as shown in this plot:
![Image_Rotation_v0 1 0](https://user-images.githubusercontent.com/14074051/72755621-3a419d80-3bcb-11ea-8c4b-ffd9fd37c3b8.png)
In order to avoid such edge effect, it would be best to keep the image a bit larger before rotation and only crop the image to the final size after rotation. But how much larger should the image be before rotation? In the worst case, you rotate the image 45° and to avoid edge effects the initial image size needs to be:
size_larger = np.sqrt(270**2+270**2)  #Pythagorean theorem
->if you compute that you will get 281.83, which is why AID wants to crop to 283 pixels. In AIDeveloper.py it is implemented like this:
        cropsize2 = np.sqrt(crop^2+crop^2)
        cropsize2 = np.ceil(cropsize2 / 2.) * 2 #round to the next even number

6.) I could not reproduce the last error you reported ("aid_bin.py", line 178, in write_rtdc...). It seems that the np.sum gives a float, which range() does not like. If the error persists in AIDeveloper_0.0.5_dev2, could you please try to either:
    replace line 178 in aid_bin.py with the following:
    index_new = np.array(range(1,int(np.sum(np.array([len(I) for I in Indices]))+1)))
or:
replace your aid_bin.py with the aid_bin in the attached zip-file:
[aid_bin.zip](https://github.com/maikherbig/AIDeveloper/files/4087786/aid_bin.zip)

7.) One more thing I should mention: You can **design your own neural net** which is then display in the drop-down menu in AID (this requires only a little bit of coding). If you want, you can have a look into model_zoo.py. Everything is explained there in detail. When starting AID, the neural net definitions are loaded from model_zoo.py and this also works for the .exe version. I will make a short video tutorial about that in the near feature.
Best wishes and happy fitting!

**Comment by andko76** [comment]
Hello Maik,

thank you very much for good explanations and support 
  to point 2.)  i will test this, because the speed is much higher with GPU ;-)
  to point 3.)  i have two links for you: 
        ->  https://github.com/heuritech/convnets-keras
        ->  https://github.com/gabrieldemarmiesse/heatmaps
        it would be fantastic, if you could implement such a heatmap function

the other point i will test and give you a feedback
greetings
André

**Comment by andko76** [comment]
Hello Maik,
i tested point 6 again, with your new version (no error), then i checked again with version dev1 (no error)  :-(( ?
Maybe i produced the error, i think i forgot to check the validation check boxes for validation data sets. If i do this again, then i get the descriped error from point 6

Point 7. i will test later, a video explanation would be fine
Sorry

**Comment by maikherbig** [comment]
AIDeveloper now supports all image dimensions. You can even have different (odd) image dimensions within the same folder: 73dc6c3
Tutorial video how to create your own neural nets is here: https://figshare.com/articles/Krater_et_al_2020_Data_zip/9902636
Thanks for the hint considering heatmaps. I will open a new issue and work on that in the future!
