### ISSUE TITLE
Being able to set up Fill mode for augmentation

### ISSUE THREAD

**Issue by alfrem** [maikherbig/AIDeveloper#10]
Would be good to be able to set up fill mode as seen in:

https://keras.io/preprocessing/image/

Thank you

**Comment by maikherbig** [comment]
I totally agree, but I don't want to use ImageDataGenerator since it is very slow. I used ImageDataGenerator at the beginning (AIDeveloper<0.0.5) but I realized that this function took in some cases longer than training. Hence, I spend a lot of time to optimize the image augmentation functions using OpenCV (see aid_img.py). (So far I could not find any other library that is faster than the implementations in aid_img.py.)
I will check if there is a way to get more fill-options using OpenCV or so.

**Comment by alfrem** [comment]
Great! Thanks.

**Comment by maikherbig** [comment]
Solved via faaf72a
