### ISSUE TITLE
512 by 512 images get cropped and padded even if input is set to 512

### ISSUE THREAD

**Issue by jonathancolledge** [maikherbig/AIDeveloper#55]
I have a problem best described by a screenshot. All my images are already 512 x 512. I have it set to a 512 input, but all the previews (either on Example imgs, or by clicking on the rtdc filename) show the processed images to be a small part of the original with huge padding.
<img width="929" alt="AI Developer 512 image 2" src="https://github.com/maikherbig/AIDeveloper/assets/4342400/fbeea823-7da8-4ff3-b88f-8ab93b11792d">
In the image above I double clicked to get the preview and the original image is fine, but the processed image is missing vital information. Please help!

**Comment by maikherbig** [comment]
Thanks for reporting. This is super weird and it may take some time to find the root cause.
I also tried a bit and it works for 510x510. The error occurs for larger images. Here are two quick workarounds (choose which one you like better):
Quick fix a) crop all images to 510 x 510
Quick fix b) crop a single image to 510 x 510 and import the whole folder to AIDeveloper. There will be a popup asking, how you want to process the images to make them equal. Here you can choose to crop/pad such that final result is 510 x 510 for all images.

Sorry for the inconvenience. I will look into it!

**Comment by maikherbig** [comment]
Issue should be solved and here is a corresponding update:
https://github.com/maikherbig/AIDeveloper/releases/tag/0.4.8-update
Please dont hesitate to reopen the issue if you have further troubles

**Comment by jonathancolledge** [comment]
@maikherbig Thank you so much!
